export enum UTIL {
  ALERT_MESSAGE_SUCCESS_ADD_MOVIE = 'Create movie successfully!',
  // tslint:disable-next-line:max-line-length
  DATE_PATTERN = '^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|(?:(?:1[6-9]|[2-9]\\d)?\\d{2})(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\5(?:0?[1-9]|1\\d|2[0-8])$|^(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00)))(\\/|-|\\.)0?2\\6(29)$|^(?:(?:1[6-9]|[2-9]\\d)?\\d{2})(?:(?:(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\8(?:29|30))|(?:(\\/|-|\\.)(?:0?[13578]|1[02])\\9(?:31)))$',
  NUMBER_PHONE_PATTERN = '^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$',
  ICON_SUCCESS = 'success',
  ICON_ERROR = 'error',
  ALERT_MESSAGE_SUCCESS_AVATAR = 'Change avatar successfully!',
  ALERT_MESSAGE_SUCCESS_DETAIL_ACCOUNT = 'Change account info successfully!',
  ALERT_MESSAGE_SUCCESS_ADD_GENRE = 'Create genre successfully!',
  DEFAULT_MOVIE_POSTER_NAME = 'default_movie.png',
  DEFAULT_MOVIE_POSTER_URL = './assets/img/image/default_movie.png',
  DEFAULT_ACCOUNT_IMAGE_NAME_MALE = 'male.png',
  DEFAULT_ACCOUNT_IMAGE_URL_MALE = './assets/img/image/male.png',
  DEFAULT_ACCOUNT_IMAGE_NAME_FEMALE = 'male.png',
  DEFAULT_ACCOUNT_IMAGE_URL_FEMALE = './assets/img/image/male.png',
  ALERT_MESSAGE_SUCCESS_ADD_DIRECTOR = 'Create genre successfully!',
  ALERT_MESSAGE_SUCCESS_ADD_CAST = 'Create cast successfully!',
  DEFAULT_IMAGE_ACCOUNTS = '121',
  DEFAULT_IMAGE_MOVIE = '221',
  DEFAULT_IMAGE_CAST = '231',
  DEFAULT_IMAGE_DIRECTOR = '241',
  ALERT_MESSAGE_SUCCESS_REMOVE_MOVIE = 'Deleted the movie successfully!',
  ALERT_MESSAGE_SUCCESS_REMOVE_ACCOUNT = 'Deleted the user successfully!',
  ALERT_MESSAGE_DELETE_MOVIE = 'Delete this movie?',
  ALERT_MESSAGE_DELETE_ACCOUNT = 'Delete this user?',
  ALERT_MESSAGE_SUCCESS_EDIT_MOVIE = 'Update movie successfully!',
  ALERT_MESSAGE_SUCCESS_ADD_ACCOUNT = "Create new user successfully!\nPassword has been sent to user's email",
  ALERT_MESSAGE_SUCCESS_EDIT_ACCOUNT = 'Update user info successfully!',
  CHANGE_PASSWORD_SUCCESSFULLY = 'Change password successfully!',
  DATE = 'dd-MM-yyyy',
  DELIMITER = '-',
  FULL_HD = '1080',
  QUALITY_FULL_HD = 'Full HD',
  HD = '720',
  QUALITY_HD = 'HD',
  WARNING_LOGIN = 'You must login!',
}
